---
title: "Line Extension Allowances in Illinois"
subtitle: " "
date: 2025-10-28
author:
  - name: Alexandra Smith
    affiliations:
      - Switchbox

keywords: line extension allowances, natural gas, future of gas, Illinois

bibliography: ../references.bib
license: "CC BY-NC"

toc: true
notebook-links: false
reference-location: margin
fig-cap: true
fig-cap-location: margin
tbl-cap-location: margin

appendix-style: default
citation-location: document
citation:
  container-title: Switchbox

# Uncomment this when PDF version has been added to local docs/
#other-links:
#  - text: PDF
#    icon: file-earmark-pdf
#    href: docs/switchbox_report.pdf
---

```{r}
library(tidyverse)
library(scales)
library(gt)
library(gtExtras)

# Import variables
load(file = "/workspaces/reports2/reports/il_lea/report_vars.RData")
```


# Executive Summary




# Background

## What are Line Extension Allowances?

Each year, Illinois gas utilities connect TK of new customers to the gas distribution system. In some cases, these customers are newly constructed buildings on brownfield sites already served by the gas network. In others, they are newly-built or existing buildings on the edge of the gas network that are being connected to the network for the first time, effectively growing the network's footprint.

When gas utilities connect these new customers, they often need to extend the pipeline network to reach them. This usually means building new service lines, and often means extending gas mains. [^main_service]

[^main_service]: "**Main**" refers to the main gas distribution line that connects to the customer's property. "**Service**" refers to the smaller line that connects to the main line and serves the customer's home.

Rather than the new gas customer paying for these "line extensions", most of the cost is covered by subsidies called Line Extension Allowances (LEAs).

These subsidies are paid for by existing gas customers through their gas bills. In effect, LEAs hide the true cost of heating a building with natural gas from the building owner, by shifting the cost of connecting the building to the gas network to all other customers.

In Illinois, new customers are not required to pay for the first 100 or 200 feet of a main extension (for low and high pressure mains, respectively), or for the first 60 feet of a new service line to connect their building to the main.

And while Illinois law only requires gas utilities to provide LEA subsidies to urban customers, most utilities also offer them to rural customers, and the ICC approves this practice.[^rural_lea]

[^rural_lea]: TK evidence for this claim

Spending on LEAs ultimately increases the revenue requirement for gas utilities, driving up bills for ratepayers for years after the initial investments are made.


## Why are states revisiting LEA policies?
Historically, LEAs were established to grow the gas distribution system, allowing utilities to capitalize on economies of scale.

There was an embedded assumption that customers would stay in the system for the long term and costs associated with LEAs would be recouped through increased revenue from the growing customer base.

Today, rising gas bills and broader awareness of the environmental damage associated with natural gas emissions are leading regulators to reevaluate the role of LEAs in the natural gas system.

As states progress towards their climate goals, they are increasingly looking to electrify buildings and transportation systems. Continued expansion of the natural gas system not only runs counter to emissions reduction targets, but also encourages additional capital investment in infrastructure that may no longer be needed in a future with reduced gas demand. [^stranded_assets]

[^stranded_assets]: "**Stranded assets**" refers to gas infrastructure—such as pipelines or distribution networks—that is rendered obsolete or uneconomic before the end of its expected useful life because customers shift away from natural gas, potentially leaving a shrinking utility ratepayers responsible for paying off investments in infrastructure they no longer use.

With the growing availability of cost-effective electric alternatives to gas heating, the historical motivations for supporting the expansion of gas infrastructure are increasingly being questioned. Eight states have passed or are currently considering legislation to limit or phase out LEA spending at the time of this report. @henchen_CuttingTheseSubsidies_2025

The Illinois Commerce Commission has expressed interest in reviewing LEA policies as part of its ongoing work on the Future of Gas. Bill SB2269, introduced in the Illinois General Assembly earlier this year would require gas utilities to charge customers for the full incremental cost of new development and growth their connection creates. [^sb2269] @villanueva_SB2269_2025

[^sb2269]: [§ 9-228.5](https://www.documentcloud.org/documents/26212423-il-sb2269-villanueva/#document/p29/a2676215): "Gas main and gas service extension policies shall be based on the principle that the full incremental cost associated with new development and growth shall be borne by the customers that cause those incremental costs. Gas main and gas service extension policies, procedures, and conditions shall align with the greenhouse gas emission reduction goals established in Article XXIV." @villanueva_SB2269_2025

# Findings
There is limited data on what gas utilities in Illinois are spending on LEA projects. We present a mix of data including historical and forecasted spending data collected from rate cases and best estimates for missing data. [^data_sources]

[^data_sources]: For more details on the data presented, please see the data table in the Appendix (@sec-data-sources).

## How much is being spent on LEAs across the state?

In 2022, the last year for which data is available, existing gas customers in Illinois paid an esitmated total of `r lea_total_all_utilities_22` on LEA subsidies. The average annual spending across all three utilities was `r lea_hist_avg_all_utilities_18to22` per year.


## How much does Nicor Gas spend on LEAs?
From `r fetch_spending_vars("from", total_spending, "nicor_main_historical")` to `r fetch_spending_vars("to", total_spending, "nicor_main_historical")`, the last year for which data is available, existing Nicor customers paid `r fetch_spending_vars("avg_cost", total_spending, "nicor_main_historical")` per year to extend gas mains, on average, and `r fetch_spending_vars("avg_cost", total_spending, "nicor_service_historical")` per year to build service lines for new customers.

Nicor is forecasted to spend a total of `r fetch_spending_vars("total", total_spending, "nicor_combined_forecast")` between `r fetch_spending_vars("from", total_spending, "nicor_combined_forecast")` and `r fetch_spending_vars("to", total_spending, "nicor_combined_forecast")` on LEA subsidies, averaging `r fetch_spending_vars("avg_cost", total_spending, "nicor_combined_forecast")` per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-nicor-spending >}}
:::

In 2023, Nicor spent and average of `r nicor_per_connect_23` in LEA subsidies for main extensions for every new connection, and an esitamted average of `r nicor_per_connect_service_23` per new service line connection. (@fig-nicor-per-connection). Nicor did not report a cost per service line connection, so the figure is based on the average reported "per project" cost, which we interpret to mean connections.[^per_project_cost]

[^per_project_cost]: "**Per project service line cost**" were calculated by subtracting the customer contribution from the total extension cost and dividing by the number of service line projects.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-nicor-per-connection >}}
:::

And these costs are growing: in the five years preceding 2023, the average main extension per connection grew by `r nicor_per_connect_change` year-on-year, on average.


## How much does Peoples Gas spend on LEAs?

From `r fetch_spending_vars("from", total_spending, "peoples_main_historical")` to `r fetch_spending_vars("to", total_spending, "peoples_main_historical")`, the last year for which data is available, Peoples Gas customers paid an average of `r fetch_spending_vars("avg_cost", total_spending, "peoples_main_historical")` per year to extend gas mains, and `r fetch_spending_vars("avg_cost", total_spending, "peoples_service_historical")` per year to build service lines for new customers.[^nonQIPP]

[^nonQIPP]: In the [ICC Docket No. 23-0068](https://www.documentcloud.org/documents/26189740-peoplesgas-p2023-0068-pio-exhibit-12-64269107/#document/p36/a2674688),Peoples Gas reported main extension costs as "NonQIP main expenditures over the last five years, **excluding customer contributions**, for projects that required main extensions. The expenditures include main related costs for the entire project." For the purpose of this report, we interpret this to mean spending on line extension allowances.

Average annual forecasted spending for `r fetch_spending_vars("from", total_spending, "peoples_main_forecast")` to `r fetch_spending_vars("to", total_spending, "peoples_main_forecast")` was `r fetch_spending_vars("avg_cost", total_spending, "peoples_main_forecast")` per year on main extensions and `r fetch_spending_vars("avg_cost", total_spending, "peoples_service_forecast")` per year on service line extensions.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-peoples-spending >}}
:::

In 2022, the last year for which data is available, Peoples Gas customers paid an average of `r peoples_per_connect_22` per new connection to extend gas mains and build service lines.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-peoples-per-connection >}}
:::

This figure combines main and service line extensions; the utility did not break down the costs by type of extension.

## How much does Ameren Gas spend on LEAs?

Ameren has denied requests to report directly on LEA spending. As an approximation, we have included material spending associated with new gas connections and the standard cost equivalent per connection for Ameren Gas.[^std_cost_equiv]

[^std_cost_equiv]: The standard cost equivalent per connection is the maximum LEA subsidy per new connection for Ameren Gas. The remainder of the connection cost is the responsibility of the customer.

Ameren has historically provided main line extension double that of other gas utilities, up to 400 feet. They are currently proposing to reduce this to 200 feet. @amerenillinoiscompany_Docket250084Ameren_2025 [^extension_reduction]

[^extension_reduction]: In the [ICC Rate Case 25-0084](https://www.documentcloud.org/documents/26460874-p2025-0084-initial-brief-73432621/#document/p211/a2777028): "Ameren Gas Company proposes to reduce the standard cost equivalent for a new natural gas connection from 400 feet to 200 feet."

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-ameren-spending >}}
:::

In 2025, the last year for which data is available, Ameren customers paid maximum of TK to extend gas mains for every new connection.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-ameren-per-sce >}}
:::

As with Nicor, this estimate covers main extensions only; it does not include service line extensions. In other words, it underestimates the true cost of connecting a new customer to Ameren's network.

# Appendix

## Acknowledgments
The authors would like to thank:

- Bradley Cebulko, Current Energy Group

## Data and Methods

### Data collected directly from rate cases {#sec-data-sources}
| Utility     | Data                                  | Source                                                                                                                                                                                                                                                                                          |
|-------------|---------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nicor       | LEA spending                          | [ICC Rate Case 23-0066](https://www.documentcloud.org/documents/26188653-nicor-p2023-0066-pio-exhibit-12-30205654/), [ICC Rate Case 25-0055](https://www.documentcloud.org/documents/26193423-nicor_p2025-0055-pio-cross-exhibit-20-51703648/)                                                 |
| Nicor       | Cost per new connection               | [ICC Rate Case 23-0066](https://www.documentcloud.org/documents/26188653-nicor-p2023-0066-pio-exhibit-12-30205654/)                                                                                                                                    |
| Peoples Gas | LEA spending                          | [ICC Rate Case 23-0068](https://www.documentcloud.org/documents/26189740-peoplesgas-p2023-0068-pio-exhibit-12-64269107/)                                                                                                                               |
| Peoples Gas | Cost per new connection               | [ICC Rate Case 23-0069](https://www.documentcloud.org/documents/26189763-peoples-gas-p2023-0069-pio-cross-exhibit-100-95312469/)                                                                                                                        |
| Ameren      | Material spending on new gas connections | [ICC Rate Case 23-0067](https://www.documentcloud.org/documents/26188848-ameren-p2023-0067-pio-exhibit-12-96925852/)                                                                                                                                  |
| Ameren      | Standard cost equivalent for new connection | [ICC Rate Case 25-0084](https://www.documentcloud.org/documents/26193410-ameren_p2025-0084-pio-exhibit-12-57399815/)     |


### Estimated data
#### Peoples Gas
Peoples Gas did not report a cost per service line connection, so the figure is based on the average reported "per project" cost, which we interpret to mean connections. [^per_project_cost]
Per project service line costs were calculated by subtracting the customer contribution from the total extension cost and dividing by the number of service line projects in each year.

Peoples Gas reported "the NonQIP main expenditures, excluding customer contributions, for projects that required main extensions. The expenditures include main related costs for the entire project". Qualified Infrastructure Plant (QIP) typically refers to infrastructure replacement or modernization projects. We cannot be certain that all of these expenses were related to line extension allowances. The figures reported here should be considered an upper bound on the true cost of main line extension allowances for Peoples Gas.

#### Nicor Gas
The total LEA spending figure was calculated by subtracting the reported  customer contribution from the reported total extension cost for main service lines in each year.

Nicor provided estiamtes of their average cost in 200 foot free main allowance per foot and per customer. We interpret per customer to mean the average cost per new connection. It is unclear if this figure would include mulitple customers per connection in the case of a multi-family building.

The per connection cost estimates for service line extensions were calculated by subtracting the reported customer contribution from the reported total extension cost for service line extensions in each year and dividing by the reported number of service line projects in each year. We assume that one project is equal to one new connection.

#### Ameren Gas
Ameren Gas did not report total LEA spending for service or main line extensions. Instead they provided data for two standing work orders (SWOs) for new business for transmission and distribution related work. The report describes **transmission SWO** includes "work for large meter sets, regulator station upgrades and SCADA when such equipment is required for acustomer load addition."" The **distribution SWO** includes "gas mains, service lines, fittings and other material associated with new service requests". For each of these SWOs, they also provided dollar values for the total Customer Contributions in Aid of Construction (CIAC). We estiamted the total LEA spending by subtracting the distribution SWO CIAC from the distribution SWO total.

Ameren Gas reported the standard cost equivalent for a new connection as 400 feet. We interpret this to mean the maximum LEA subsidy per new connection. The remainder of the connection cost is the responsibility of the customer. There was no data on the actual average cost per connection, so we used the standard cost equivalent which should be considered an upper bound.


## Assumptions

TK fill this out.

## References

::: {#refs}
:::
