# Changes here will be overwritten by Copier
_commit: v1.4.2
_src_path: https://github.com/switchbox-data/data-science-project
author: Switchbox
author_github_handle: switchbox-data
aws: true
email: hello@switch.box
open_source_license: MIT license
project_description: This repo contains Switchbox's reports.
project_features:
- python_data_science
- r_data_science
use_github: true

