# Markdown flavor and line width
flavor = "quarto"
line-width = 120
line-ending = "auto"

[format]
wrap = "reflow"

# External code formatters (opt-in)
[formatters]
python = "ruff"
r = "air"
yaml = "yamlfmt"

[formatters.ruff]
args = ["format", "--stdin-filename", "$FILENAME", "--line-length", "120"]
stdin = true

[formatters.air]
args = ["format", "--preset=tidyverse"]

# External code linters
[linters]
r = "jarl"
