name: Run in devcontainer
description: "Run a command in a devcontainer shell"
inputs:
  runCmd:
    description: command to run
    required: true

runs:
  using: "composite"
  steps:
    - shell: /usr/bin/bash -e -c "devcontainer exec --workspace-folder . bash -e - < '{0}'"
      run: ${{ inputs.runCmd }}
