shortcodes:
  - ../../lib/quarto_extensions/glossary/glossary.lua
filters:
  - at: pre-quarto
    path: ../../lib/quarto_extensions/icml_gt/icml_gt.lua
  - at: pre-quarto
    path: ../../lib/quarto_extensions/icml_floats/icml_floats.lua
  - path: ../../lib/quarto_extensions/icml_math/icml_math.lua
project:
  type: manuscript
  output-dir: docs
  render:
    # - notebooks/bat_by_utility_investigation.qmd
    # - notebooks/data_quality.qmd
    - notebooks/tou_investigation.qmd
    - notebooks/analysis.qmd
    - notebooks/gold_book_peaks.qmd
    - notebooks/cost_of_service_by_subclass.qmd
    - notebooks/investigate_household_savings.qmd
    - notebooks/fair_default_feasible_line.qmd
    - index.qmd
manuscript:
  article: index.qmd
fig-format: svg
format:
  html:
    page-layout: article
    smooth-scroll: true
    link-external-window: true
    toc-depth: 3
    toc-expand: false
    theme:
      - ../.style/switchbox.scss
    include-in-header: ../.style/notebook-preview.html
    include-after-body: ../.style/switchbox.html
