shortcodes:
  - ../../lib/quarto_extensions/glossary/glossary.lua
project:
  type: manuscript
  output-dir: docs
  render:
    # - notebooks/bat_by_utility_investigation.qmd
    # - notebooks/data_quality.qmd
    - notebooks/analysis.qmd
    - notebooks/gold_book_peaks.qmd
    # - notebooks/cost_of_service_by_subclass.qmd
    - index.qmd
manuscript:
  article: index.qmd
format:
  html:
    page-layout: article
    smooth-scroll: true
    link-external-window: true
    toc-depth: 3
    toc-expand: 2
    theme:
      - ../.style/switchbox.scss
    include-in-header: ../.style/notebook-preview.html
    include-after-body: ../.style/switchbox.html
    fig-format: svg
