---
title: "All-Electric Building Act"
subtitle: "The impact of the AEBA on the grid"
date: 2025-10-26
author:
  - name: Juan-Pablo Velez
    orcid: 0009-0000-5203-1536
    email: jpv@switch.box
    affiliations:
    - Switchbox
  - name: Bryan Murray
    orcid: 0009-0008-4505-0657
    email: bryan@switch.box
    affiliations:
    - Switchbox
    - University of Oviedo

bibliography: ../references.bib
license: "CC BY-NC"

toc: true
notebook-links: false
reference-location: margin
fig-cap: true
fig-cap-location: margin
tbl-cap-location: margin

appendix-style: default
citation-location: document
citation:
  container-title: Switchbox

# Uncomment this when PDF version has been added to local docs/
#other-links:
#  - text: PDF
#    icon: file-earmark-pdf
#    href: docs/switchbox_report.pdf
---

# Introduction

In May 2023, New York became the first state to pass a law requiring all new buildings to be all-electric: the **All-Electric Building Act** (AEBA).

On January 1, 2026, the first part of the AEBA will take effect: residential buildings seven stories and less will be required to be all-electric, as well as commercial and industrial buildings 100,000 square feet and less.[^residentialcommercial]

[^residentialcommercial]: The AEBA will apply to all new buildings, with a few exemptions, starting on January 1, 2029; see [§11-104-6(b)](https://www.nysenate.gov/legislation/laws/ENG/11-104) of the New York State Energy Conservation Construction Code.

As the state looks ahead to the launch of the nation's first all-electric new construction standard, Switchbox is releasing this analysis of the AEBA's impact on the reliability of New York's electric grid.

In the wake of two grid reliability reports from the New York Independent System Operator (NYISO), moderate Democrats in the New York State Assembly are pushing Gov. Hochul to delay implementing the AEBA she signed into law in 2023.[^news]

[^news]: As first reported by [spectrum news](https://spectrumlocalnews.com/nys/central-ny/politics/2025/10/21/moderate-assembly-dems-push-hochul-to-delay-all-electric-buildings-mandate) [@katelisa_ModerateAssemblyDems_2025].

Claiming that "NYISO has flagged serious [grid reliability] concerns that warrant a more cautious approach", moderate Democrats in the New York State Assembly have sent a letter to Gov. Kathy Hochul, asking her to "suspend enforcement of the new building electrification requirement" until the state "evaluates grid readiness under high electrification".[^letter]

[^letter]: The [sign-on letter](https://www.documentcloud.org/documents/26205362-letter-to-gov-kathy-hochul-requesting-pause-of-all-electric-building-act-implementation-2025/) was authored by Assemblymember William Conrad (D-AD 140).

Despite asserting that NYISO's reliability reports warrant delaying the AEBA's implementation, the letter includes no analysis of how the law—which only applies to _new_ buildings—would actually affect the grid.

To shed some light on the grid impacts of the AEBA, this report seeks to answer the following questions:

- Will the AEBA actually spur "high electrification", given the state's expected pace of new construction?
- How will the AEBA actually affect the grid?
- What do NYISO's recent reliability reports actually say? Do their findings warrant a delay to the AEBA?


# Executive Summary

Analyzing data from NYISO and the Census Bureau, this report finds that:

- AEBA will increase electricity use from buildings in winter, not summer. Nearly all new construction already uses air-conditioning.
- Today, New York's grid has significant spare capacity in the winter—the winter peak is only 75% of the summer peak.
- The short-term reliability needs identified by NYISO (for the next five years) are all associated with the summer peak.
- Therefore, the AEBA will not contribute to short-term reliability issues. Rather, it will make better use of the grid's spare capacity.
- Over the long-term, a growing winter peak, driven partly by heating electrification, will eventually exceed the summer peak. (Estimates vary on when this will happen.)
- However, given New York's current and expected pace of new construction, the AEBA will be responsible for only 2% of the winter peak growth.

# Findings

# Appendix

## Acknowledgments

## Data and Methods

## Assumptions

## References
