project:
  type: website
  title: "reports2"
  render:
    - md_example.qmd
    - index.qmd
    - py_example.qmd
    - r_example.qmd

website:
  title: "reports2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: md_example.qmd
        text: Markdown Example
      - href: py_example.qmd
        text: Python Example
      - href: r_example.qmd
        text: R Example

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
