all: clean render

# Delete all caches
clean:
    rm -rf .quarto docs/*_files/ notebooks/*_files/ notebooks/*.html \
           notebooks/*.ipynb notebooks/*.rmarkdown

# Render quarto project
render:
    quarto render .

today := `date +%Y%m%d`
draft_name := "report_draft_" + today + ".docx"
draft:
    quarto render index.qmd --to docx --output {{ draft_name }}

publish:
    bash -c 'parent_folder=$(basename $(pwd)); pub_path="../../docs/$parent_folder"; \
    rm -rf "$pub_path" && mkdir -p "$pub_path" && cp -r docs/* "$pub_path"'

download_data:
    dvc pull '/workspaces/reports/data/ResStock/2022_resstock_amy2018_release_1.1/rs_ma_hp_rates_2.db.dvc'
    dvc pull '/workspaces/reports/data/utility_rates/electric/madpu/ma_mlp_delivery_tariffs.rds'
    dvc pull '/workspaces/reports/data/ma_hp_rates/annual_change.db'
