all: clean render

clean:
    uv run python -m lib.just.clean

render:
    uv run python -m lib.just.render

today := `date +%Y%m%d`
draft_name := "report_draft_" + today + ".docx"

draft:
    quarto render index.qmd --to docx --output {{ draft_name }}

typeset_name := "report_" + today + ".icml"

typeset:
    quarto render index.qmd --to icml --output {{ typeset_name }}

publish:
    uv run python -m lib.just.publish

diff label="":
    uv run python -m lib.just.diff {{ label }}
