project:
  type: manuscript
  output-dir: docs
  render:
    - notebooks/analysis.qmd
    - notebooks/cost_of_service_by_subclass.qmd
    - notebooks/feeder_peaks.qmd
    - notebooks/delivery_cost_timing.qmd
    # - testimony_outline.qmd
    - index.qmd
manuscript:
  article: index.qmd
format:
  html:
    page-layout: article
    smooth-scroll: true
    link-external-window: true
    theme:
      - ../.style/switchbox.scss
    include-in-header: ../.style/notebook-preview.html
    include-after-body: ../.style/switchbox.html
    fig-format: svg
