---
title: "Heat Pump Rates in Rhode Island"
subtitle: "A Detailed Analysis of Proposed Winter Season Delivery Rates for Heat Pump Customers in Existing Construction"
date: 2025-10-30
author:
  - name: Bryan Murray
    orcid: 0009-0008-4505-0657
    email: bryan@switch.box
    affiliations:
      - Switchbox
  - name: Juan-Pablo Velez
    orcid: 0009-0000-5203-1536
    email: jpv@switch.box
    affiliations:
      - Switchbox

keywords: air-source heat pumps, electric rates, rate design, rhode island

bibliography: ../references.bib
license: "CC BY-NC"

toc: true
notebook-links: false
reference-location: margin
fig-cap: true
fig-cap-location: margin
tbl-cap-location: margin

appendix-style: default
citation-location: document
citation:
  container-title: Switchbox

# Uncomment this when PDF version has been added to local docs/
#other-links:
#  - text: PDF
#    icon: file-earmark-pdf
#    href: docs/switchbox_report.pdf
---

```{r}
#| label: index-setup
library(tidyverse)
library(scales)
library(gt)
library(gtExtras)

source("/workspaces/reports2/lib/ggplot/switchbox_theme.R")

# Import variables
load(file = "/workspaces/reports2/reports/ri_hp_rates/cache/report_variables.RData")
```

# Introduction
TK

# Executive Summary
TK

# Background
TK

# Scope and Assumptions
TK

# Findings

## What happens to a home's energy bills after switching to heat pumps?

### Gas Customers
:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-stacked_bar_median_before_after_gas >}}
:::

- On the far left we see the median electric bill under baseline rates, across the whole state, with the current mix of home heating fuels and current electric rates.
  - The customer charge and volumetric delivery charge are what's collected by Rhode Island Energy to pay for the poles and wires that deliver electricity to the home.
  - The supply charge is just a pass-through; it reflects what Rhode Island Energy pays for the electricity on the wholesale market.
- The second column shows the median electric bill for heat pump customers under baseline rates. Heat pump customers pay higher _electricity_ bills but typically save overall by reducing other fuels costs.
- Importantly, the higher delivery charges means heat pump customers are paying more for the _poles and wires_ that deliver electricity to the home, even though they are not contributing to the grid's peak load (and thus not contributing to the capital costs of new infrastructure).

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_gas_before >}}
:::

- Breaking the bills down by month shows the expected pattern: total energy bills are higher in the winter months, and gas bills are markedly higher due to heating loads.
- Since heating is the largest single energy end-use, and these homes use natural gas for heating
  - the gas bill is the largest component of the total bill,
  - and the electric bill remains relatively stable throughout the year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_gas_after >}}
:::

- The before-upgrade total bill is in light red.
- Using today's electric rates, the median monthly bills doesn't change much after heat pump installation.

### Fuel Oil Customers
- Households that use fuel oil for heating see a similar pattern: electric consumption goes up, but fuel oil consumption goes down dramatically, and so the median overall whole-home energy bill is lower.

- The small residual fuel oil cost is because the furnance remains in the home as backup heating, and even though it's not used much, some fuel oil is still consumed.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-stacked_bar_median_before_after_fuel_oil >}}
:::

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_fuel_oil_before >}}
:::

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_fuel_oil_after >}}
:::

### Electric Resistance Customers
- Electric resistance customers save immediately, consistently, and substantially when switching to a high-efficiency cold-climate heat pump.
- Since they are not switching _fuels_, only technologies, and since we're only considering today's electric rates (that is, no technology-specific rates), the efficiency advantage from heat pumps leads very directly to bills savings.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-stacked_bar_median_before_after_resistance >}}
:::

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_resistance_before >}}
:::

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-monthly_bills_resistance_after >}}
:::

## What is the statewide bill impact of switching to heat pumps?
- The previous section considered the _median_ bill of an _individual_ home.
- All homes are different, and may see different results.
- What is the range of expected total household bill impacts?

### Bill impact under default rates, in the winter

- As we can see from the monthly bills above, bills are higher in the winter months, regardless of heating system. Rhode Island winters are cold!

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_winter_bill_impact >}}
:::

### Bill impact under default rates, in the summer

- Summer bills are lower than winter bills overall, and so they are less impactful to annual household budgets.
- This is reflected in the tigher spread. More homes are in the small savings/small increase categories.
- Nevertheless, homes that switch to heat pumps in the summer will, by definition, also have cooling for the summer months. For some homes, this is a new comfort, but also a new, optional cost.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_summer_bill_impact >}}
:::

## How does a home's baseline heating system affect its energy bills after switching to heat pumps?
- The statewide findings in preceding sections help us assess the overall impact of electric rate designs on heat pump operating costs. But they also mask important differences in how homes' current heating systems affect their heating bills after they make the switch.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-bar-fuel-types >}}
:::

- **@fig-bar-fuel-types** gives a breakdown of the heating systems currently used by homes in Rhode Island. A majority (`r round(fuel_types_pct |> filter(hvac_group == "Natural Gas") |> pull(pct) * 100)`%) of Rhode Island homes use natural gas as their primary heating fuel, while significant portions use fuel oil (`r round(fuel_types_pct |> filter(hvac_group == "Fuel Oil") |> pull(pct) * 100)`%) and electric resistance (`r round(fuel_types_pct |> filter(hvac_group == "Electric Resistance") |> pull(pct) * 100)`%).

### Natural Gas Customers
- Among natural gas-heated homes that switch to heat pumps under today's electric rates, about a third (`r annual_change_stats_gas_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases, but very few (`r annual_change_stats_gas_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_natural_gas_annual_change >}}
:::

### Fuel Oil Customers
- Among fuel oil-heated homes that switch to heat pumps under today's electric rates, one in six (`r annual_change_stats_fuel_oil_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases, but like the natural gas customers, very few (`r annual_change_stats_fuel_oil_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_fuel_oil_annual_change >}}
:::

### Electric Resistance Customers
- Among electric resistance-heated homes that switch to heat pumps under today's electric rates, only a handful (`r annual_change_stats_resistance_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see an a small increase in their bills.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_resistance_annual_change >}}
:::

## How does the building type a home is in affect its energy bills after switching to heat pumps?
- A home's construction and size certainly impact total energy consumption, and thus the bill magnitude.
- **@fig-bar-building-type** gives a breakdown of the building types currently used by homes in Rhode Island. A majority (`r round(building_type_pct |> filter(building_type_group == "Single-Family") |> pull(pct) * 100)`%) of Rhode Island homes are single-family homes, and the rest are multi-family buildings split among 2-4 unit buildings (`r round(building_type_pct |> filter(building_type_group == "2-4 Units") |> pull(pct) * 100)`%) and 5+ unit multifamily buildings (`r round(building_type_pct |> filter(building_type_group == "5+ Units") |> pull(pct) * 100)`%).

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-bar-building-type >}}
:::

### Single-Family Homes
- A quarter (`r annual_change_stats_single_family_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) of single-family homes would see bill increases, but very few (`r annual_change_stats_single_family_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_single_family_annual_change >}}
:::

### 2-4 Unit Multifamily Buildings
- Only a quarter (`r annual_change_stats_small_multifamily_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases, but none (`r annual_change_stats_small_multifamily_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_small_multifamily_annual_change >}}
:::

### 5+ Unit Multifamily Buildings
- Similarly, only one-third (`r annual_change_stats_small_multifamily_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) of large multifamily buildings would see bill increases, but again, none (`r annual_change_stats_small_multifamily_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_large_multifamily_annual_change >}}
:::

## How does a home's current AC affect its energy bills after switching to heat pumps?

- Note: our priors on the results in this section are:
  - Home-wide AC: bills go down
  - AC in some rooms: bills may go up or down
  - No AC: bills go up

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-bar-cooling-types >}}
:::

- **@fig-bar-cooling-types** gives a breakdown of the cooling systems currently used by homes in Rhode Island. A majority (`r round(cooling_type_pct |> filter(baseline_cooling_type_group == "Room AC") |> pull(pct) * 100)`%) of Rhode Island homes use have room-by-room AC (e.g. window units), while a large minority (`r round(cooling_type_pct |> filter(baseline_cooling_type_group == "Central AC") |> pull(pct) * 100)`%) have central AC (e.g. through ducts). There is also a small but important group (`r round(cooling_type_pct |> filter(baseline_cooling_type_group == "No Cooling") |> pull(pct) * 100)`%) of homes that have no cooling.

### Homes with Room AC
- Among room AC-cooled homes that switch to heat pumps under today's electric rates, a quarter (`r annual_change_stats_room_ac_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases but none (`r annual_change_stats_room_ac_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_room_ac_annual_change >}}
:::

### Homes with Central AC
- Among central AC-cooled homes that switch to heat pumps under today's electric rates, a quarter (`r annual_change_stats_central_ac_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases, and only a small handful (`r annual_change_stats_central_ac_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) would face an increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_central_ac_annual_change >}}
:::

### Homes with No Cooling
- Among homes currently with no cooling at all that switch to heat pumps under today's electric rates, just under half (`r annual_change_stats_no_cooling_baseline_hp_high |> filter(bill_category == "pct_that_lose") |> pull(percentage)`%) would see bill increases.
- It's important to now that this gain of function is _good_ thing, because these homes now have air conditioning where previously they did not.

For a small handful (`r annual_change_stats_no_cooling_baseline_hp_high |> filter(bill_category == "large_increase") |> pull(percentage)`%) this gain of function leads to a bill increase of more than $1,000 per year.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_no_cooling_annual_change >}}
:::

## How does a home's income affect its energy bills after switching to heat pumps?
### Energy Burdens
- So far we've discussed energy bills in dollar terms, but the more direct question is: how do energy expenses fit into a home's budget?
- This is the crux of **affordability**, because the relative impact of bill changes will depend on the home's income.
- One common metric for affordability is the **energy burden**, the percentage of a home's annual income spent on energy.
- Policymakers typically consider households with energy burdens above 6% to be highly burdened.
- **@fig-burden_hists_all_smi_tiers** shows the distribution of energy burdens for all fuel types, all building types, all cooling types, all income levels.
  - Assuming 100% participation in low-income discounts.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-burden_hists_all_smi_tiers >}}
:::

- Overall, energy burdens in Rhode Island are high. The spread of energy burdens for the current mix of home heating fuels and today's electric rates is the top histogram in **@fig-burden_hists_all_smi_tiers**. Across all income levels, heating and cooling arrangements, building types and occupancy levels, `r burden_hists_all_current_pct_burdened`% of homes are considered to be energy burdened (spending >6% of home's annual income on energy bills), with `r burden_hists_all_current_pct_very_high_burden`% of homes being very high energy burdened (spending >12% of home's annual income on energy bills).
- The spread of energy burdens does not change much when switching to heat pumps under today's heating mix and electric rates (the bottom histogram in **@fig-burden_hists_all_smi_tiers**). Across all income levels, heating and cooling arrangements, building types and occupancy levels, `r burden_hists_all_hp_high_pct_burdened`% of homes are energy burdened, with `r burden_hists_all_hp_high_pct_very_high_burden`% of homes being very high energy burdened (spending >12% of home's annual income on energy bills).

### Energy Burden by Income Level
- How does energy burdens look for different household income levels?
- **@fig-bar_smi_tiers** shows the distribution of homes' income, grouped into tiers by State Median Income (SMI).

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-bar_smi_tiers >}}
:::

- SMI is defined by both the household's income and the number of occupants in the household.
- SMI is a common classification of relative income.
- SMI is also used to determine eligibility for the low-income discount programs. Typically, households with an income less than 60% of the SMI are eligible for a discount on electricity and gas bills. They might also be eligible for other programs like LIHEAP.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-scatter_income_burden_total >}}
:::

- **@fig-scatter_income_burden_total** shows a clear inverse relationship between energy burden and household income: as income increases, energy burden decreases.
- In other words, low- and moderate-income households spend a larger share of their income on energy than high-income households.
- Because of the outsized effect of energy bills on low- and moderate-income households, we should look closer at how seasonal discount rates would impact households of different income levels, as shown in **@fig-burden_hists_3_smi_tiers_current** for 3 SMI tiers:
  - Low Income (<60% SMI, top histogram),
  -  Moderate Income (60–100% SMI, middle histogram),
  - and Not LMI (>100% SMI, bottom histogram).

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-burden_hists_3_smi_tiers_current >}}
:::

- The difference is stark: `r burden_hists_low_smi_current_pct_burdened`% of low-income households are energy burdened, compared to `r burden_hists_moderate_smi_current_pct_burdened`% of moderate-income households and `r burden_hists_not_lmi_current_pct_burdened`% of not LMI households.
- Especially worrying is that `r burden_hists_low_smi_current_pct_very_high_burden`% of low-income households are very highly energy burdened.


How do energy burdens change when switching to heat pumps under today's electric rates?
- Not much at all.
- In **@fig-burden_hists_3_smi_tiers_hp_high** we see that the energy burden distribution is essentially the same for all income levels as with today's current HVAC mix.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-burden_hists_3_smi_tiers_hp_high >}}
:::


# Appendix
## Correlated Housing Characteristics
:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-housing_units_pairs_plot >}}
:::

- this shows the correlations between the housing characteristics
- Most single-family homes have gas heat and AC
- most high-income households are in single-family homes


## How does heat pump efficiency impact savings?
:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hists_3_bills_by_hp_model_baseline_rates >}}
:::


ResStock 2024 has 3 different heat pump models, specified by HSPF: 9.2, 11, and 13.

  - `hp_low` is for 9.2 HSPF heat pumps, which is the minimum efficiency heat pump required for Energy Star certification.
  - `hp_mid` is for 11 HSPF heat pumps, a high-efficiency, inverter-driven 'cold-climate' heat pump.
  - `hp_best` is for 13 HSPF heat pumps, representing the top end of the market for currently-available heat pumps, or a expected typical model in coming years.

- Under baseline rates...

  - `hp_low` heat pumps means about 50% of homes would save
  - `hp_mid` heat pumps means about 75% of homes would save
  - `hp_best` heat pumps means about 90% of homes would save


## Acknowledgments

## Data and Methods

## Assumptions

- We refer to Rhode Island Energy, which was formerly known as National Grid d.b.a. Naragansett Electric Company. PPL acquired Naragansett Electric Company in 2022 from National Grid and rebranded as Rhode Island Energy.
- We assume all eligible customers participate in the low-income discount program for gas and electric delivery. (TK: This aligns with @e3_NearTermRateDesign_2024)
- We ignore the 30% discount for Medicaid eligible customers; they get "just" the 25% discount for households below the 60% state median income threshold. Read documentation for the LMI discounts [here](https://www.documentcloud.org/documents/26078361-ri-low-income-ratepayers-discount-and-funding-sources-regulatory-topic-overview-04-2024/#document/p1/a2669185).


## References
