all: clean render

clean:
    uv run python -m lib.just.clean

render:
    uv run python -m lib.just.render

draft:
    quarto render index.qmd --to docx --output report_draft.docx

typeset:
    quarto render index.qmd --to icml

publish:
    uv run python -m lib.just.publish

diff label="":
    uv run python -m lib.just.diff {{ label }}
