```{r}
library(tidyverse)
library(duckdb)

all_gas_rates_filled <- read_csv("/workspaces/reports/data/utility_rates/gas/madpu/gas_supply_rates_tidy_filled.csv")

all_gas_rates_filled <- all_gas_rates_filled %>%
  filter(rate_class %in% c('R-1', 'R-2', 'R-3', 'R-4'))

path_rs_db <- '/workspaces/reports/data/ResStock/2022_resstock_amy2018_release_1.1/rs_ma_hp_rates_2.db'
```



```{r}
# Create plot of supply rates over time by utility
all_gas_rates_filled |>
  ggplot(aes(x = effective_date, y = supply_rate, color = gas_utility)) +
  geom_line(data = . %>% filter(gas_utility != "unitil")) +
  geom_line(data = . %>% filter(gas_utility == "unitil"),
            color = "red", size = 2) +
  scale_y_continuous(labels = scales::label_dollar()) +
  labs(
    title = "Massachusetts Gas Supply Rates",
    x = "Date",
    y = "Supply Rate ($/therm)",
    color = "Utility"
  ) +
  theme_minimal()



```


```{r}
# Write to database
# con <- DBI::dbConnect(duckdb::duckdb(), path_rs_db)
# DBI::dbWriteTable(con, "supply_rates_gas", all_gas_rates_filled, overwrite = TRUE)
# DBI::dbDisconnect(con)

```
