---
title: "Who saves when switching to heat pumps, and why?"
subtitle: "A Quantitative Survey of Factors Impacting Heating Bills"
date: 2025-12-13
author:
  - name: Bryan Murray
    orcid: 0009-0008-4505-0657
    email: bryan@switch.box
    affiliations:
      - Switchbox
  - name: Alex Hyumnin Lee
    email: lee@switch.box
    affiliations:
      - Switchbox
  - name: Juan-Pablo Velez
    orcid: 0009-0000-5203-1536
    email: jpv@switch.box
    affiliations:
      - Switchbox

keywords: air-source heat pumps, electric rates

bibliography: ../references.bib
license: "CC BY-NC"

toc: true
notebook-links: false
reference-location: margin
fig-cap: true
fig-cap-location: margin
tbl-cap-location: margin

appendix-style: default
citation-location: document
citation:
  container-title: Switchbox

# Uncomment this when PDF version has been added to local docs/
#other-links:
#  - text: PDF
#    icon: file-earmark-pdf
#    href: docs/switchbox_report.pdf
---

# Introduction

# Executive Summary

# Foundation: Relative Fuel Prices and System Efficiency
- Here we include Lee's inequality: **A home will save money if the ratio of electric heating efficiency to gas heating efficiency is greater than the ratio of electric rates to gas rates**
$$ \frac{COP_{eff}}{\eta_{furnace}} > \frac{Electric Rate}{Fossil Fuel Rate} $$

- In other words, is the electric heating sufficiently more efficient to offset the relatively higher per-kWh electricity rate?

## Right Side: Fuel Rates
- The ratio of electricity rates to gas rates is the same for any given combination of electric and gas utilities.
- Rhode Island is a good example because there is only one utility for both electric and gas: Rhode Island Energy.
- Electricity is ~3x cheaper per kWh than natural gas for Rhode Island Energy customers.
  - That means that the electric heating upgrade must be at least 3x more efficient than the natural gas heating basline to realize operating cost savings.

### Electricity prices in New England
- Cite: Wiser et al, 2025

## Left Side: Heating System Efficiency
- The left side of the inequality is the ratio of the heat pump's efficiency to the furnace's efficiency.
- Even within a territory, this ratio is not constant, but rather depends on the pre-upgrade furnance efficiency and post-upgrade heat pump efficiency.
  - What's more, the heat pump efficiency is not constant, but rather depends on the relative temperature difference between the indoor and outdoor air. Heat pumps are less efficient in colder temperatures, as we expect daily in the overnight hours.
  - That means that the _pattern_ of a home's heating energy consumption matters too, not just the monthly total.
- Generally, heat pumps are ~3x more efficient than fossil furnaces and electric resistance heaters.
- This factor of 3 is about the same as the ratio of electricity rates to gas rates in Rhode Island, meaning that whether or not a home sees operational cost savings can vary home-by-home, depending on its appliance efficiency and consumption pattern.

# Device Efficiency
## Isolating Heating Bills
- Just looking at the _change_ in the _volumetric_ **heating** bill
  - heating: only considering the heating load
  - volumetric: just multiplying the consumption by the combined supply and delivery rates
  - change: the difference between the pre- and post-upgrade volumetric heating bills
- The volumetric heating bill change for Natural Gas customers is shown in @fig-hist_1_annual_change_heating_baseline_hp_high.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_1_annual_change_heating_baseline_hp_high >}}
:::

- Most homes will see the heating portion of their bills increaase.
- That is, the left side of the inequality is less than the right side for most homes.

## Heating Bill Changes by Furnace Efficiency
- Since we established that the right side of the inequality is the same for all homes in our Rhode Island sample, we can say that whether or not a device saves will depend on the the old furnance efficiency and the new heat pump efficiency.
- How does the old furnance's efficiency impact the bill _change_?
- We see a clear trend in @fig-plot_heating_bill_change_vs_afue: customers with more efficient furnances see larger bill increases when switching to heat pumps.
- Why? Assuming that a given home has the same heating load before and after the heat pump installation, and that both the furnace and the heat pump can meet this need in every hour of the year. However, homes with less-efficient furnaces had to burn more fuel to meet that heating load, mean a higher pre-upgrade heating bill, and relatively better operating cost changes compared to homes with more efficient furnaces.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-plot_heating_bill_change_vs_afue >}}
:::

### Isolating Furnace Efficiency
- Most folks have a furnance with nominal AFUE of 80%
- Do we still see large variance among these homes?
- @fig-hist_3_heating_bill_changes_by_afue shows the distribution of bill changes for homes with 3 different baseline furnace efficiencies.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_3_heating_bill_changes_by_afue >}}
:::


## Estimating Heat Pump Efficiency
- HP efficiency is not constant, but rather depends on relative temperature difference between the indoor and outdoor air.

### Backup Heating
- Electric resistance backup heaters have an efficiency of 100% (COP = 1.0). Although necessary at times, backup heating will reduce the overall electric heating efficiency (combined efficiency of the heat pump and the backup electric resistance heater).


# Impacts on Bills: Rhode Island Example
## Load Profiles
- Running at night is generally less efficient
- Poorly insulated homes (that is, with less thermal inertia) have work harder when the temp is low
- So the house insulation and heating *pattern* is also a factor in the monthly consumption, and thus the bill

## Floor area as a proxy for heating loss
- cite Bernard, 2025

# Zooming Out: Dynamic Tariffs and Grid Impacts

## Grid Impacts
- hourly consumption pattern is also important for grid impacts
- Expect the winter peak will be at the

### Winter vs Summer Peak Loads
- Most homes now have a winter peak/summer peak ratio of TK%
- @fig-hist_4_winter_peak_load_pct_by_upgrade shows the distribution of winter peak load as a percentage of summer peak load for homes with 4 different upgrades.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_4_winter_peak_load_pct_by_upgrade >}}
:::

- What we really care about is the overall peak on the grid relative to the current peak. This is a proxy for the grid upgrades that might be needed.
- @fig-hist_3_annual_peak_growth_by_upgrade shows the distribution of annual peak load as a percentage of baseline peak load for homes with 3 different upgrades.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-hist_3_annual_peak_growth_by_upgrade >}}
:::

- This research is important because it can predict which kinds of customers will see the largest growth peak load.
- With these characteristcs, grid planners can beter model which feeders are most likely to need upgrades.


## Dynamic Tariffs
- Example: Cosy Octopus
  - which roughly tracks _supply_ prices


## Tariffs for Distribution Grid Impacts
- How does heat pump adoption impact the distribution grid?
- A TOU tariff should incentivize consumption away from the individual feeders' peaks...but how do we know that peak time?



# Appendix
## Due Diligence

### Total Heat Delivered
- Does the total heat delivered stay the same for a given bldg_id across upgrades?
  - because one core assumption is that $\int_{t_0}^{t_{\text{end}}} HL(t)$ is constant
  - "the home's temperature controller meets its objective"

- No! As we can see in @fig-plot_heating_load_change, the heating load for a given home is not always the same across upgrades.
- TK% have a negligible change in heating load.
- TK% show a heating load increase less than 10%, and another TK% show a heating load increase of more than 10%.
- TK% show a heating load decrease, most of which (TK%) are less than 10%.

:::{.column-page-inset-right}
{{< embed notebooks/analysis.qmd#fig-plot_heating_load_change >}}
:::

- What can we say about the homes that have higher heating loads after electrification?



## Acknowledgments

## Data and Methods

## Assumptions

## References
